### PR TITLE
Windows Port

### PR DESCRIPTION
**Pull request by jtesta**
This adds support for 32-bit and 64-bit Windows builds.  An executable can be created by one of the following ways:  1.) By cross-compiling from a Linux host machine, 2.) By compiling under Windows using MinGW/Mingw-w64, and 3.) By compiling under Windows using Visual Studio Express 2013 for Desktop (this is the free version; others are untested).

### CODE REVIEW

**Comment by rbsec** [comment]
This is something that's been requested in the past, but I've got no experience of Windows C/socket programming, so it didn't really go anywhere. I remember there was an old fork of sslscan for Windows (based on 1.8.2), but it's badly outdated now. Thanks very much for picking this up.

I've done some (quick) tests with this on Linux and it's working fine, but I'd like to make sure I can get it building under Windows before merging this into master. I'm not really going to be able to provide much support for the Windows fork (and have little desire to try and debug any random Windows issues that turn up), but from a quick look through the diff it doesn't look like there's anything that should cause too many problems. I'll do some tests and let you know if I run into any problems.

Thanks

~rbsec

**Comment by jtesta** [comment]
Sure, no problem!

I don't mind helping out with debugging Windows issues from time to time.  There may be times that I'm not very responsive, but I'll do what I can.  Other people can certainly jump in with patches from time to time, too, after all.

Would you be interested in putting a compiled binary into the repo?  End users would find that extremely useful, since most of them don't have development toolchains, nor know how to use them.

In other news, spoke with Ian Whiting in December and January, and he said that he is resuming development on the official version "soon".  Perhaps you can reach out and see if its possible to merge this fork back in.  Otherwise, if there's going to be two competing sslscan's out there, it might be less confusing to people if this fork's name is changed... to, say... tlsscan?  Just a thought.

**Comment by sarak** [comment]
Is it possible to publish (on GitHub or other site) Windows port binary files for tests?

**Comment by rbsec** [comment]
With both the native Linux and cross-compiled binaries working fine, I'm happy to merge this into master. I've not had a chance to try natively building it with VS on Windows, but that's something I'll look into.

A Windows binary is a very good idea (as you say, most people don't have a setup to compile stuff on Windows). I'll need to think about exactly how to do this; some browsers throw warnings about unsigned binaries, so it might be a good idea to get a signed binary.

It's very interesting to hear that the original author is planning to bring sslscan back to live (after it's been dead so long). There are a few different forks out there (mine is based on ioerror's, and there's at least one other fork that's had development in the last year that uses Python for output processing). This kind of fragmentation is pretty inefficient, as I imagine we're all looking to implement similar features.

Unless Ian is wanting to go in a completely different direction from this version, I don't really see much benefit to maintaining the two different versions. I don't have any direct contact details for him, so if you're in touch then could you either pass on my details or a link to this discussion? There are a number of possible ways we could handle a merge/transition, so I'm sure we can work something out.

Thanks again for your work on the Windows port, I'm sure a lot of people will appreciate it.

~rbsec

**Comment by jtesta** [comment]
Great!  FYI, Visual Studio produces a binary that is about 10% smaller 
in size.  Its much more difficult to install, though, since you need to 
download gigabytes between that and some other tools.  And if you're 
primarily a Linux guy like me, its a lot easier to just cross-compile 
than fire up a VM every time.  But I figured that some people out there 
would appreciate VS support, so I threw it in.

I think signing binaries is a good idea.  In the meantime, though, 
perhaps you can push them out unsigned and let users themselves decide 
if they like that or not.  Notice how fast someone asked us for a 
binary?  It seems users are really itching for this...

Browsers seem to be OK with zipped executables.

I'll send an e-mail to both you and Ian, and we'll try to get a 
discussion going.

**Comment by rbsec** [comment]
I thought that a VS binary would probably be better (and it seems much cleaner to have natively compiled rather than cross-compiled) - but I don't have VS setup at home, and don't really want to install it in a VM just for this. I do have VS setup at work though, so I can give it a try there when I have some free time. Code signing is probably simpler with VS than trying to do it with the cross-compiled version.

I've uploaded a ZIP containing a cross-compiled exe and a GPG signature on the [releases page](https://github.com/rbsec/sslscan/releases). Although TBH, anyone who's downloading a prebuilt Windows binary probably isn't going to bother verifying the signature. Still, it's better than nothing.

Looking forward to hear from Ian.

~rbsec

**Comment by sarak** [comment]
Thanks :)

**Pull request merged**
