### PR TITLE
Added cipher id to output (stdout and XML)

### PR DESCRIPTION
**Pull request by maurice2k**
Added SSL cipher id to output for easy matching.

### CODE REVIEW

**Comment by rbsec** [comment]
Thanks for the PR. Cipher IDs isn't a feature that I've ever really wanted - generally the cipher suite names are enough (although most MS tends to use different names) - but I can see that people would find this useful. However, since it's a slightly niche feature I think it would be better as a non-default option, because it adds quite a lot of clutter to the output that most people won't be interested in (and means the output doesn't fit in a standard 80 char terminal). Perhaps --show-cipher-ids.

A few other comments on the output:

* On stdout you pad the cipher IDs with zeros, but the XML output doesn't do this. I don't have a strong preference either way (different people do this different ways), but I think that it should be the same between stdout and the XML. Not padding them will be messy or complicated on stdout (to keep the details aligned), so it might be better to pad both of them, although for the vast majority of ciphers the first byte will be 0x00, so that's a bit of a waste of space.
* In the RFCs they use capital letters in the hex output (%X rather than %x) - although some other places use lowercase. Again, no strong preference.
* I don't think the brackets around the cipher ID are needed, we don't use them elsewhere in the output.

These are pretty minor things. I'll have play with the output and look at merging this when I have a little more time.

Thanks,

~rbsec

**Comment by maurice2k** [comment]
Thanks for your feedback!

I adjusted the code so that cipher ids are only shown on stdout when using `--show-cipher-ids` option.
The ids are always formatted using %X but with no padding (same for stdout and XML). For stdout the ids are aligned.

`--show-cipher-ids` only controls output on stdout; the ids are always included in the XML. Otherwise the option should be renamed to --include-cipher-ids or something like that.

Best regards,
Moritz

**Comment by maurice2k** [comment]
image

**Comment by rbsec** [comment]
Fantastic, I've merged it into master and updated the man page with the new options.

Thanks,

~rbsec

**Pull request merged**
