### PR TITLE
New Kali git URL

### PR DESCRIPTION
**Pull request by g0tmi1k**

### CODE REVIEW

**Comment by g0tmi1k** [comment]
Any reason pointing to the git repo?
Is it worth saying in Kali: `apt install sslscan` with it or instead of?

**Comment by rbsec** [comment]
@g0tmi1k 

I've merged this and also updated the readme with a note saying to install it with `apt` as a first option.

Thanks

**Comment by g0tmi1k** [comment]
Thank you!

**Comment by g0tmi1k** [comment]
@rbsec 
Will there be a new release soon? The last one happened `31 Dec 2017`

**Pull request merged**
