### PR TITLE
Sometimes we need to determine the list of acceptable CAs for client authentication

### PR DESCRIPTION
**Pull request by kyprizel**

### CODE REVIEW

**Comment by rbsec** [comment]
Thanks for the PR. This isn't a circumstance I've had to test personally (client auth is depressingly rare, and where I've seen it it's been on IIS which doesn't seem to return anything for this).

Few other comments from a quick read through the code:

* On line 2302 we're checking that the return value from SSL_connect() is 1, and only continuing if it is. But if we don't have a proper client cert, SSL_connect() will fail and return 0, and we won't get a list of CAs. If this check changes to (cipherStatus >= 0) that seems to work - can you test this against your system?
* I've prefer not to use --quiet as it's a big vague (and there's some discussion about it supressing any secure output in #23), so could we rename this to --no-preferred (keeping it in line with the other options to disable various checks).
* Rather than having a skipPreferredCiphers option, can we have a 'preferredCiphers' option which defaults to 1, and set that to 0 if --no-preferred is passed as an argument (to be consistent with the rest of the options).
* Would the --show-client-auth option be better as --show-client-cas? Or --show-client-calist or something? Not sure...

You've also reminded me that I need to update the changelog (I tagged a release as 1.9.9 but forgot to  update that).

**Comment by rbsec** [comment]
Actually, thinking about it, does this even need an option? Given that the majority of systems don't support client auth (so won't send a CA list) could this be something we display by default in the certificate info if it's returned? Most of the time there'll be not list of CAs returned, so it shouldn't be obtrusive.

**Comment by kyprizel** [comment]
Yes, you right, SSL_connect() should be checked against 0.
skipPreferredCiphers changed to getPreferredCiphers and set to true by default.
Options names changed.
I'm not sure if we should run showTrustedCAs on every scan - it's one more connection.

**Comment by rbsec** [comment]
Merged, and updated the manpage to reflect the new options (and warn that IIS doesn't seem to return a CA list).

**Comment by kyprizel** [comment]
Thanks!

**Pull request merged**
