### PR TITLE
enable SSLv2 when configuring openssl for static builds

### PR DESCRIPTION
**Pull request by earlfogel**
Add SSLv2 support to the openssl we build with 'make static'.

### CODE REVIEW

**Comment by rbsec** [comment]
Even with that compile flag, it looks like the 40/56 bit ciphers are disabled (there are a load of `#if 0`), so this is only a partial fix.

I re-enabled both of them by building against the `OpenSSL_1_0_2f` tag, which still has  support for both. This may cause problems down the line when new features/ciphers get introduced that sslscan needs, but it'll do for now.

If you get the latest version of sslscan from the repo and do a `make static` then it should scan SSLv2 again, I fixed it in 5eea559e33dba453f077936bb1663580c436346c earlier today.

**Comment by earlfogel** [comment]
Thanks, it's hard to keep up. :-)

If you want SSLv2 and weak ciphers with the most recent OpenSSL, you can use:

 ./config no-shares enable-ssl2 enable-weak-ssl-ciphers

**Comment by rbsec** [comment]
Are you sure about that option? From the quick look I had at one of the recent commits in the `OpenSSL_1_0_2` branch it looked like they were just [disabled](https://github.com/openssl/openssl/commit/9dfd2be8a1761fffd152a92d8f1b356ad667eea7#diff-26cfb6e51c2d6028c1adde8cff1bc532R159), because the `#if 0` should never be true. That `enable-weak-ssl-ciphers` doesn't seem to be anywhere in the OpenSSL report (according to GitHub's search), but it's mentioned in the changelog on their site...

I'll have a proper look into this when I get a chance, it looks like there are also some changes to `SSLv23_method()` which might need changes in sslscan to be compatible. Building against the `OpenSSL_1_0_2f` tag works for now (although it's not a good long term solution), so that give me a bit of time..

**Comment by rbsec** [comment]
Using `enable-ssl2 enable-weak-ciphers` seems to work fine, so I've updated the makefile to that and reverted the change to use the `OpenSSL_1_0_2f` tag. I've also retagged `1.11.2-rbsec` with the new fix.

Thanks,

~rbsec

**Comment by earlfogel** [comment]
Sounds good.

Earl

**Comment by rbsec** [comment]
Turns out using those two options is incomplete. Fixed it properly with a slightly nasty hack in e8c48b74eb7edc5d8d15e75a32bde60b13e98112:

```
The previous fix of using enable-ssl2 and enable-weak-ciphers was
incomplete, because the 40 and 56bit SSLv2 ciphers were still disabled.
There's no option to re-enable them - they're commented out with #if 0
statements.

Building against a previous tag will mean missing out on future
features, so as a workaround the Makefile now replaces those #if 0
statements with #if 1 to re-enable the ciphers.

Bit of a bodge, but doesn't seem to break anything, and will allow us to
keep building against the latest version.
```

**Comment by earlfogel** [comment]
I built the latest version and it works like a charm.  Thanks!

Earl

**Pull request closed without merging**
