### PR TITLE
Fix of the patching of the DH size 

### PR DESCRIPTION
**Pull request by bgabrhelik**
on BSD based systems like OS X where basic RegEx is by default.

### CODE REVIEW

**Comment by bgabrhelik** [comment]
Build tested on macOS Sierra (10.12) and  centos 7.2.

**Comment by mschilt** [comment]
'-E' switch oes not seem to exist in GNU sed used on Linux.

**Comment by bgabrhelik** [comment]
Well  -E swich is not documented on man page, but it works and is there for ages. It's a shortcut for --regexp-extended
see here: https://www.gnu.org/software/sed/manual/sed.html#BRE-vs-ERE
As BRE in BSD and Linux world is not compatible I didn't find another portable solution than use ERE.
Here is how POSIX defines BRE and ERE
 https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man7/re_format.7.html#//apple_ref/doc/man/7/re_format
OK I will revisit it it seems that x\+ can be replaces by xx* i.e. in this case 
[0-9]\+ -> [0-9][0-9]*
I will test whether it would work in BRE on both platforms.

**Comment by mschilt** [comment]
You are right. This option is well-hidden (http://git.savannah.gnu.org/cgit/sed.git/tree/sed/sed.c#n323)
In that case it looks good for me.

**Pull request closed without merging**
