### PR TITLE
Update to OpenSSL 3.0

### PR DESCRIPTION
**Pull request by tetlowgm**
Did some light testing on MacOS and FreeBSD (I didn't have a Linux host around) and verified it still works against known bad sites at badssl.com. Also change the OpenSSL compilation step to only build the libraries instead of the whole application since we don't need anything other than the libs for our purposes.

### CODE REVIEW

**Comment by rbsec** [comment]
I've done some initial testing with OpenSSL 3 on Linux, and (surprisingly) nothing seems to be broken. A few of the cipher names have changed (which causes a some of the tests in Docker to fail), but the detection seems correct. I'll need to do some more testing through to see if I can find any edge cases.

@jtesta any thoughts on this?

**Comment by jtesta** [comment]
@rbsec : I tested this PR and it (mostly) looks good.  Two minor issues:

1. OpenSSL v3.0 detects `TLS_RSA_WITH_IDEA_CBC_SHA` in some Docker tests where v1.1.1 didn't report it.  I suspect that, for some reason, we were missing this ciphersuite previously.
2. The `openssl-3.0` branch that this PR uses includes all dev changes (whereas we were using `OpenSSL_1_1_1-stable` to track the latest stable release).  Unfortunately, I don't see a `-stable` equivalent for v3.0.  Stable releases seem to be tracked in explicit branch names only, like `openssl-3.0.10`.  This means we would need to write additional logic in the Makefile to find the latest stable branch ourselves and use it.  I can submit a PR for this if you'd like.

Aside from the stray IDEA ciphersuite I mentioned above, all failing Docker tests are the result of renamed ciphersuites (i.e.: `DHE-RSA-SEED-SHA` -> `TLS_RSA_WITH_SEED_CBC_SHA`); everything else is the same.

Overall, this PR seems good to merge.

And FYI: while there is an OpenSSL v3.1, this has a much shorter lifecycle than v3.0, which is an LTS release supported for another 3+ years (see https://endoflife.date/openssl).  So it makes sense to stick with v3.0.

**Comment by rbsec** [comment]
It's rather irritating that there's no v3.0-latest branch for us to use, but there we go. TBH, I'm ont really sure how much we gain from following the latest v3.0-stable, as it may mean our build randomly breaking when upstream changes something. But then since they'll be implementing security fixes it may be better to automatically follow those rather than having to manually test and update every time they release.

Agreed that it's not worth following v3.1 - we don't care about any of the new features or performance improvements in it, so the LTS v3.0 is better for us.

**Comment by rbsec** [comment]
I've pushed a [new branch](https://github.com/rbsec/sslscan/tree/openssl_3) `openssl_3` which builds against the latest OpenSSL `3.0.x` tag, and I've updated the tests to address the cipher suite changes (and fixed a bug with the TLSv1.3 ciphers not being shown in green when they should have been). Will need to do some more testing before I merge though.

**Comment by rbsec** [comment]
The mingw build seems to work fine with OpenSSL 3.0, and the exe works as expected (although TBF I've only tested it in wine).

**Comment by jtesta** [comment]
@rbsec : FYI, after 5 years of support, OpenSSL v1.1.1's lifecycle ends in a week and a half from today (see https://endoflife.date/openssl).

**Comment by rbsec** [comment]
@jtesta thanks for the nudge about this. I hadn't completely forgotten it, but I'm afraid that this project isn't something that I've had much time for lately.

The OpenSSL 3.0 build seems to be working reasonably well on both Linux and the Windows binary - so I've merged this and bumped the version up to 2.1.0 - I guess we'll see soon enough if there are any major bugs.

Thanks as always.

**Pull request merged**
