### PR TITLE
Added option for OCSP stapling request

### PR DESCRIPTION
**Pull request by kelbyludwig**

### CODE REVIEW

**Comment by kelbyludwig** [comment]
If anyone has opinions on the output let me know. I tried to simplify it from what OpenSSL shows but maybe I still print too much info.

**Comment by rbsec** [comment]
Thanks for the PR, I've had a play with it (not that many sites actually support OCSP, which is a little worrying), and the code seems good.

The output is fairly verbose, but it's not included in the default output so I don't have a problem with that. Any chance you could rebase this before I merge it in to keep the repo history a bit cleaner?

~rbsec

**Comment by kelbyludwig** [comment]
I squashed my commits. Let me know if I need to do anything else prior to the merge. Thanks!

**Comment by rbsec** [comment]
Looks good, so I've merged it. I'll work on adding XML support (#52) at some point.

Thanks,

~rbsec

**Comment by oranze** [comment]
In XML no OCSP result

**Pull request merged**
